version: '3'

services:
  app:
    container_name: nextjs
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 49153:49153
    volumes:
      - .:/usr/src/app
      - /usr/src/node_modules
