Fields: {}
Relationships:
  Parent: 
  OneToMany: 
  ManyToOne: 
Slots:
  Model:
    Imports: 
    Extends: 
    Ctor: 
    Body: 
  Logic:
    Imports: 
    Init: 
    OnCreateInstance: 
    OnGetList: 
    OnGetSingle: 
    BeforeSave: 
    AfterSave: 
    BeforeRemove: 
    AdapterOut: 
    Body: 
  Gateway:
    Imports: 
    Endpoints: 
    EndpointsRoutes: 
  Service:
    Dependencies: 
    AdapterIn: 
    AdapterOut: 
    Body: 
Name: Project
Type: 
Table: 